version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smart-wallet-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=wallet_db
      - POSTGRES_USER=wallet_user
      - POSTGRES_PASSWORD=wallet_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: